name: Update Dynamictest Datei

permissions:
  contents: write

on:
  schedule:
    - cron: '0 12 * * *'  # Täglich um 12:00 UTC – passe den Zeitplan bei Bedarf an
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: dynamictest.txt aktualisieren
        run: |
          echo "Aktualisiere dynamictest.txt mit den neuen Werten..."
          cat > dynamictest.txt <<'EOF'
HarvestAmountMultiplier=2.5
TamingSpeedMultiplier=5.0
XPMultiplier=2.5
MatingIntervalMultiplier=0.02
BabyMatureSpeedMultiplier=40.0
EggHatchSpeedMultiplier=60.0
BabyImprintAmountMultiplier=20.0
HexagonRewardMultiplier=1.0
EOF

      - name: Änderungen committen und pushen
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dynamictest.txt
          git commit -m "Automatische Aktualisierung der dynamictest.txt" || echo "Keine Änderungen"
          git push


