name: Update Dynamictest Datei

on:
  schedule:
    - cron: '0 12 * * *'  # Täglich um 12:00 UTC – passe den Zeitplan bei Bedarf an
  workflow_dispatch:     # Ermöglicht auch manuelles Auslösen

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: dynamictest.txt aktualisieren
        run: |
          echo "Aktualisiere dynamictest.txt mit den neuen Werten..."
          cat > dynamictest.txt <<'EOF'
TamingSpeedMultiplier=1.0
HarvestAmountMultiplier=1.0
XPMultiplier=2.0
MatingIntervalMultiplier=0.5
BabyMatureSpeedMultiplier=2.0
EggHatchSpeedMultiplier=2.0
BabyCuddleIntervalMultiplier=0.6
BabyImprintAmountMultiplier=2.0
HexagonRewardMultiplier=1.0

      - name: Änderungen committen und pushen
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dynamictest.txt
          git commit -m "Automatische Aktualisierung der dynamictest.txt" || echo "Keine Änderungen"
          git push
